site_name: Rubiks Cube Solver
nav:
  - Home: index.md
  - Demo: demo.md
theme:
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/rubik.png'
  palette:
    primary: 'grey'
    accent: 'blue'
