site_name: Rubik's Cube Solver
nav:
  - Home: index.md
  - Code Docs: implementation.md
  - Quick Start: quickstart.md
theme:
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/rubik.png'
  palette:
    primary: 'grey'
    accent: 'blue'
